[package]
name = "ed25519-dalek-bip32-feeless"
version = "0.1.1"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/feeless/feeless/tree/main/external/ed25519-dalek-bip32"
documentation = "https://docs.rs/ed25519-dalek-bip32/"
description = "Simplified ed25519 BIP32 derivations"
keywords = ["derivation", "BIP32", "ed25519", "trezor", "blockchain"]
categories = ["cryptography", "no-std"]

[features]
default = ["std"]
std = ["derivation-path/std", "sha2/std", "ed25519-dalek/std"]

[dependencies]
derivation-path = { version = "0.1.3", default-features = false }
sha2 = { version = "0.9.1", default-features = false }
hmac = { version = "0.9.0", default-features = false }
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["u64_backend", "rand"] }
thiserror = "1"

[dev-dependencies]
hex = "0.4.2"
