name: ci 
on: push
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: | 
          sudo pip3 install docker
          docker ps