name: ci 
on: push
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: | 
          sudo apt update
          sudo apt install -y python3 pip3
          sudo pip3 install docker