name: ci 
on: push
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: apt update && apt install -y python3 pip3 && pip3 install docker