name: ci 
on: push
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo pip3 install docker

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Checkout Code
        run: python3 test.py